### ISSUE TITLE
Ethereum Sync error in 1.5.0 3145775

### ISSUE THREAD

**Issue by dslutej** [LedgerHQ/ledger-live-mobile#1050]
#### Ledger Live Version and Operating System

1.5.0 (**3145775**)
Motorola One Vision
Android 9

Ledger Nano-X

#### Expected behavior

Synchronizes nicely. Can add ETH account. 

#### Actual behavior

Synchronization error.
Tried cache clear.
Tried data clear.
Tried reinstalling.
Fail at adding Ethereum account. 

#### Steps to reproduce the behavior

See above. 

Note: Tried on another phone (Moto G4) with 1.5.0 (**1048622**). Worked nicely.

**Comment by dslutej** [comment]
You guys need to work on your customer support... Anyhow, here is more info as relayed to Ledger Support representative:

Upgrading Moto G4 to latest Ledger LIve Mobile version yielded:  1.5.0 (**1048623**) and synchronization worked. 

Attaching screenshot. This is on the (non working) 1.5.0 (3145775) when trying to add the ETH account from Ledger Nano X. Accounts that worked without problem: BTC, ZEC, LTC, XRP. 

![Screenshot_20190926-203926](https://user-images.githubusercontent.com/22919263/65753052-6c0b9180-e10e-11e9-8ad4-9cdc0c8ec26e.png)

**Comment by dslutej** [comment]
Could somebody explain what the significance of the number in parenthesis after the version, i.e. 1.5.0 (**3145775**) is and how it relates to github versions? Also why is it different between phones.

**Comment by dslutej** [comment]
Extracted APKs from respective phone, unpacked and compared, results: 

Moto G4, lib = **armeabi-v7a**
Moto One Vision = **arm64-v8a**

**Comment by dslutej** [comment]
Uninstalled arm64-v8a version from Moto One (installed from PLAY) and installed the armeabi-v7a manually. **IT WERKS!**

**Comment by gre** [comment]
thanks for the report. we'll investigate. cc @KhalilBellakrid  @MortalKastor

**Comment by dslutej** [comment]
@gre any news?

**Comment by stepoleg1** [comment]
Any news? Same issue here.
Samsung s8 active Android 9

**Comment by dslutej** [comment]
*makes angry noises*

**Comment by Platinumwrist** [comment]
This is happening on Moto g7; well for last three day's or so

**Comment by yvjos** [comment]
Error Syncronized ETH in my MotoG7 Power Android 9 (Spanish), I report this probem with support but  not resolved

**Comment by yvjos** [comment]
This is Crazy.... I test now in Moto G6 and work fine.....%$"$$.... I see in Moto G6 about app is 1.5.0 (1048623) and in my Moto G7 in about is 1.5.0 (3145775) and not work (problem synchronize ETH account)...... What is the different????

**Comment by yvjos** [comment]
Where I download manual this version 1.5.0 (1048623)(not in googlePlay)???

**Comment by dslutej** [comment]
@yvjos You can use an app (from Play Store) called "Apk Extractor" to get the APK from your Moto G6. 
You then need to uninstall Ledger Live from Moto G7, transfer APK from G6 to G7 and install manually - allowing unknown sources. You should then disable Play Store from auto-updating applications. Play Store will say that there is a newer version.

I've created a separate issue/request to publish APKs. Should be a no-brainer really. But no response.

**Comment by Platinumwrist** [comment]
Thanks very much

**Comment by yvjos** [comment]
Ready... Perfect... I got the app 1.5.0 (1048623) from the G6 with Apk extractor. I put it in my G7 and installed. Now works fine. Thank you. I will send you some Bat.

**Comment by yvjos** [comment]
Please the development team Ledger release a new version to correct this problem.

**Comment by dslutej** [comment]
1.6.0 has been released and it seems to solve the issue. Or, to quote, Play Store's "**what's new**":

"Minor Fixes."

**Comment by dslutej** [comment]
Maybe the internal discussion on their JIRA were intense but not reflected here. Which is a lousy setup to being with if you really are open source. 

But the communication or lack thereof is reaaaally bad for your business guys. 

Then again, somebody decided that JavaScript was a suitable foundation to build this on...

**Comment by gre** [comment]
except most of these bugs are not due to JavaScript but to explorers and our internal (C++) lib (JS is mainly just the interface, our backends/internal libs are in fact not in JS). 

@dslutej the bug is fixed in your side? We plan to deploy a second batch of fixes soon.

**Comment by stepoleg1** [comment]
1.6.0 didn't help me at all. The strange thing is newly added Eth account syncs well. The old one doesn't. Cleaning cache / re-install doesn't help

**Comment by dslutej** [comment]
1.6.0 did not solve the issue. It seems to work until a new transaction is sent to account. Then it's back to sync error.

**Comment by dslutej** [comment]
When bashing JS-choice I was referring to app desktop+mobile. Once upon a time JS infected the browsers, and became standard. Now it is infecting apps. 🤪 Possibly I am just getting old and grumpy. Possibly.

**Comment by dslutej** [comment]
Status: does not work with 2nd largest crypto on common android phones incl android one devices. 

Several weeks now. Devs and Support show abismal interest.

**Comment by gre** [comment]
We're sorry you are experiencing issues but as I said, we are actively working on the problem and expect to fixes mobile sync issues in a second batch of fixes.
We expect this to happen in context of #1058 PR.

**Comment by cthepot-ledger** [comment]
Fix has been provided.
