### ISSUE TITLE
Polkadot (DOT) account transaction history missing

### ISSUE THREAD

**Issue by rblaine95** [LedgerHQ/ledger-live-mobile#1963]
#### Ledger Live Version and Operating System

- tested on Ledger Live `2.33.0 (289)`
- Phone version: iPhone SE (2020) with iOS 15.1

#### Expected behavior

Polkadot (DOT) account transactions should show up in transaction history automatically.

#### Actual behavior

Polkadot (DOT) transaction history doesn't show up at all.
Account total balance is correct, but transaction history is completely missing.
Advanced Logs say account was last synchronized at 2AM on 1 January 1970 (Unix Epoch, I assume)

#### Steps to reproduce the behavior

* Delete existing Polkadot (DOT) account from Ledger Live mobile
* Re-import account from Ledger Live Desktop

**Comment by rblaine95** [comment]
Fixed in latest 2.35.0 (312) release

**Comment by mihailks** [comment]
I still have the same issue. Polkadot transaction history doesn't show up at all. The total balance is correct. Anyone know how to sync the history?
